version: "3.9"  # optional since v1.27.0
services:
  node-app:
    build: .
    image: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules # Remove this if you have pure JS dependencies